-- ************ TABLAS
-- ************ Datos para la relacion 04 - DML

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';
SET LINESIZE 150
SET PAGESIZE 50
-- ************ TABLAS PARALEER Y LEIDOS **************

DROP TABLE PARALEER cascade constraints; 

CREATE  TABLE  PARALEER
(
  COD_LIBRO  NUMBER(3),
  NOMBRE_LIBRO VARCHAR2(40)
);

DROP TABLE LEIDOS cascade constraints; 

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

CREATE  TABLE  LEIDOS
(
  COD_LIBRO  NUMBER(3),
  FECHA  DATE
);

INSERT INTO PARALEER values(100,'Cien A�os de Soledad');
INSERT INTO PARALEER values (200,'Los Mitos Griegos');
INSERT INTO PARALEER values (300,'El Camino');

INSERT INTO LEIDOS values(300, '20/02/1999');
INSERT INTO LEIDOS values(200, '11/04/1999');

COMMIT;

-- ************ TABLA ALUM, NUEVOS, ANTIGUOS ************

DROP TABLE ALUM cascade constraints;
DROP TABLE NUEVOS cascade constraints;
DROP TABLE ANTIGUOS cascade constraints;

Create TABLE ALUM
(
  NOMBRE VARCHAR2(20),
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
);

Create TABLE  NUEVOS
(
  NOMBRE  VARCHAR2(20),
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
);

Create TABLE ANTIGUOS
(
  NOMBRE  VARCHAR2(20),
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
);

INSERT INTO ALUM VALUES('JUAN',18,'COSLADA');
INSERT INTO ALUM VALUES('PEDRO',19,'COSLADA');
INSERT INTO ALUM VALUES('ANA',17,'ALCALA');
INSERT INTO ALUM VALUES('LUISA',18,'TORREJON');
INSERT INTO ALUM VALUES('MARIA',20,'MADRID');
INSERT INTO ALUM VALUES('ERNESTO',21,'MADRID');
INSERT INTO ALUM VALUES('RAQUEL',19,'TOLEDO');

INSERT INTO NUEVOS VALUES('JUAN',18,'COSLADA');
INSERT INTO NUEVOS VALUES('MAITE',15,'ALCALA');
INSERT INTO NUEVOS VALUES('SOFIA',14,'ALCALA');
INSERT INTO NUEVOS VALUES('ANA',17,'ALCALA');
INSERT INTO NUEVOS VALUES('ERNESTO',21,'MADRID');

INSERT INTO ANTIGUOS VALUES('MARIA',20,'MADRID');
INSERT INTO ANTIGUOS VALUES('ERNESTO',21,'MADRID');
INSERT INTO ANTIGUOS VALUES('ANDRES',26,'LAS ROZAS');
INSERT INTO ANTIGUOS VALUES('IRENE',24,'LAS ROZAS');

COMMIT;

-- ************ TABLA PERSONAL, PROFESORES, CENTROS ***********

DROP TABLE PERSONAL cascade constraints; 

CREATE TABLE PERSONAL (
 COD_CENTRO   NUMBER(4) NOT NULL,
 DNI NUMBER(10),
 APELLIDOS VARCHAR2(30),
 FUNCION VARCHAR2(15),
 SALARIO NUMBER (10) 
);

INSERT INTO PERSONAL VALUES (10,1112345,'Martinez Salas, Fernando','PROFESOR', 220000);
INSERT INTO PERSONAL VALUES (10,4123005,'Bueno Zarco, Elisa', 'PROFESOR', 220000);
INSERT INTO PERSONAL VALUES (10,4122025,'Montes Garcia, M.Pilar', 'PROFESOR', 220000);
INSERT INTO PERSONAL VALUES (15,1112345,'Rivera Silvestre, Ana','PROFESOR', 205000);
INSERT INTO PERSONAL VALUES (15,9800990, 'Ramos Ruiz, Luis','PROFESOR', 205000);
INSERT INTO PERSONAL VALUES (15,8660990, 'De Lucas Fdez, M.Angel','PROFESOR', 205000);
INSERT INTO PERSONAL VALUES (22,7650000, 'Ruiz Lafuente, Manuel','PROFESOR', 220000);
INSERT INTO PERSONAL VALUES (45,43526789, 'Serrano Laguia, Maria','PROFESOR', 205000);
INSERT INTO PERSONAL VALUES (10,4480099,'Ruano Cerezo, Manuel','ADMINISTRATIVO', 180000);
INSERT INTO PERSONAL VALUES (15,1002345,'Albarran Serrano, Alicia','ADMINISTRATIVO', 180000);
INSERT INTO PERSONAL VALUES (15,7002660,'Mu�oz Rey, Felicia','ADMINISTRATIVO', 180000);
INSERT INTO PERSONAL VALUES (22,5502678,'Marin Marin, Pedro','ADMINISTRATIVO', 180000);
INSERT INTO PERSONAL VALUES (22,6600980, 'Peinado Gil, Elena','CONSERJE', 175000);
INSERT INTO PERSONAL VALUES (45,4163222, 'Sarro Molina, Carmen','CONSERJE', 175000);

DROP TABLE PROFESORES cascade constraints; 
CREATE TABLE PROFESORES (
 COD_CENTRO   NUMBER(4) NOT NULL,
 DNI          NUMBER(10),
 APELLIDOS VARCHAR2(30),
 ESPECIALIDAD VARCHAR2(16) 
);


INSERT INTO PROFESORES VALUES (10,1112345,'Martinez Salas, Fernando','INFORMATICA');
INSERT INTO PROFESORES VALUES (10,4123005,'Bueno Zarco, Elisa', 'MATEMATICAS');
INSERT INTO PROFESORES VALUES (10,4122025,'Montes Garcia, M.Pilar', 'MATEMATICAS');
INSERT INTO PROFESORES VALUES (15,9800990, 'Ramos Ruiz, Luis',	'LENGUA');
INSERT INTO PROFESORES VALUES (15,1112345,'Rivera Silvestre, Ana',	'DIBUJO');
INSERT INTO PROFESORES VALUES (15,8660990, 'De Lucas Fdez, M.Angel','LENGUA');
INSERT INTO PROFESORES VALUES (22,7650000, 'Ruiz Lafuente, Manuel','MATEMATICAS');
INSERT INTO PROFESORES VALUES (45,43526789, 'Serrano Laguia, Maria','INFORMATICA');

DROP TABLE CENTROS cascade constraints; 
CREATE TABLE CENTROS (
 COD_CENTRO   NUMBER(4) NOT NULL,
 TIPO_CENTRO  CHAR(1),
 NOMBRE VARCHAR2(30),
 DIRECCION VARCHAR2(26),
 TELEFONO VARCHAR2(10),
 NUM_PLAZAS NUMBER(4)
 );


INSERT INTO CENTROS VALUES (10,'S','IES El Quijote', 'Avda. Los Molinos 25', '965-887654',538);
INSERT INTO CENTROS VALUES (15,'P','CP Los Danzantes', 'C/Las Musas s/n','985-112322',250);
INSERT INTO CENTROS VALUES (22,'S', 'IES Planeta Tierra', 'C/Mina 45','925-443400',300);
INSERT INTO CENTROS VALUES (45,'P', 'CP Manuel Hidalgo', 'C/Granada 5','926-202310',220);
INSERT INTO CENTROS VALUES (50,'S', 'IES Anto�ete', 'C/Los Toreros 21','989-406090',310);

commit;
PURGE recyclebin;
SELECT * FROM PARALEER;
SELECT * FROM LEIDOS;
SELECT * FROM ALUM;
SELECT * FROM NUEVOS;
SELECT * FROM ANTIGUOS;
SELECT * FROM PERSONAL; 
SELECT * FROM PROFESORES; 
SELECT * FROM CENTROS; 
-- ************ FIN ****************





